name: lucid_clip
description: Modern clipboard manager app
version: 1.0.0+1
publish_to: none

environment:
  sdk: '>=3.8.0 <4.0.0'

#drift_version: &drift_version ^2.22.1

dependencies:
  # Core
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2
  supabase_flutter: ^2.10.3
  clipboard: ^3.0.8
  crypto: ^3.0.3
  pasteboard: ^0.4.0
#  flutter_context_menu: ^0.4.1
  contextmenu: ^3.0.0
  toastification: ^3.0.3
  metalink_flutter: ^1.0.2
  flutter_portal: ^1.1.4

  drift: ^2.29.0
  drift_flutter: 0.2.7
#  drift: 2.26.1
#  drift_flutter: ^0.2.7

  # State Management
  bloc: ^9.1.0
  flutter_bloc: ^9.1.1
  hydrated_bloc: ^10.1.1
  equatable: ^2.0.5
  iconsax: ^0.0.8
  window_manager: ^0.5.1
  proper_filesize: ^1.0.2

  # Dependency Injection
  get_it: ^9.2.0
  injectable: ^2.4.4

  # Networking
  dio: ^5.4.3+1
  json_annotation: ^4.9.0

  # Local Storage
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  flutter_secure_storage: ^10.0.0

  # Firebase
  firebase_core: ^4.3.0
  firebase_crashlytics: ^5.0.6
  firebase_auth: ^6.1.3

  # UI & Images
  cached_network_image: ^3.3.1
  flutter_staggered_grid_view: ^0.7.0
  shimmer: ^3.0.0
  google_fonts: ^6.2.1

  # Platform Services
  permission_handler: ^12.0.1
  device_info_plus: ^12.3.0
  package_info_plus: ^9.0.0

  # Utilities
  path_provider: ^2.1.3
  url_launcher: ^6.2.6
  flutter_dotenv: ^6.0.0
  tinycolor2: ^3.0.1
  share_plus: ^12.0.1
  uuid: ^4.5.1
  hugeicons: ^1.1.4
  recase: ^4.1.0
  jiffy: ^6.3.2

  # Navigation
  auto_route: ^10.1.0+1
  melos: ^6.3.2

dev_dependencies:
  # Testing
  bloc_test: ^10.0.0
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  drift_dev: ^2.29.0

  # Code Generation
  flutter_gen_runner: ^5.6.0
  build_runner: ^2.4.9
  injectable_generator: ^2.6.2
  json_serializable: ^6.8.0
  #  hive_generator: ^2.0.1
  auto_route_generator: ^10.0.1
  flutter_launcher_icons: ^0.14.4
  # Static Analysis
  very_good_analysis: ^9.0.0

flutter:
  uses-material-design: true
  generate: true

  assets:
    - .env
    - assets/images/

flutter_gen:
  output: lib/generated/
  line_length: 80

  integrations:
    flutter_svg: true

melos:
  useRootAsPackage: true
