name: lucid_clip
description: Modern clipboard manager app
version: 1.0.0+1
publish_to: none

environment:
  sdk: ^3.5.0

drift_version: &drift_version ^2.22.1

dependencies:
  # Core
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0
  supabase_flutter: ^2.10.3
  clipboard: ^2.0.2
  crypto: ^3.0.3
  pasteboard: ^0.4.0
  drift: *drift_version
  drift_flutter:  ^0.2.7


  # State Management
  bloc: ^8.1.4
  flutter_bloc: ^8.1.6
  hydrated_bloc: ^8.1.0
  equatable: ^2.0.5
  iconsax: ^0.0.8
  window_manager: ^0.5.1

  # Dependency Injection
  get_it: ^7.7.0
  injectable: ^2.4.4

  # Networking
  dio: ^5.4.3+1
  json_annotation: ^4.9.0

  # Local Storage
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  flutter_secure_storage: ^9.0.0

  # Firebase
  firebase_core: ^3.6.0
  firebase_crashlytics: ^4.1.3
  firebase_auth: ^5.3.1

  # UI & Images
  cached_network_image: ^3.3.1
  flutter_staggered_grid_view: ^0.7.0
  shimmer: ^3.0.0
  google_fonts: ^6.2.1

  # Platform Services
  permission_handler: ^11.3.1
  device_info_plus: ^10.1.0
  package_info_plus: ^8.0.0

  # Utilities
  path_provider: ^2.1.3
  url_launcher: ^6.2.6
  flutter_dotenv: ^5.0.2
  tinycolor2: ^3.0.1
  share_plus: ^10.1.2



  # Navigation
  auto_route: ^9.2.2
  melos: ^6.3.2


dev_dependencies:
  # Testing
  bloc_test: ^9.1.7
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  drift_dev: *drift_version

  # Code Generation
  build_runner: ^2.4.9
  injectable_generator: ^2.6.2
  json_serializable: ^6.8.0
#  hive_generator: ^2.0.1
  auto_route_generator: ^9.0.0
  flutter_launcher_icons: ^0.14.4
  # Static Analysis
  very_good_analysis: ^6.0.0

flutter:
  uses-material-design: true
  generate: true

  assets:
    - .env
    - assets/images/

flutter_gen:
  output: lib/generated/
  line_length: 80


melos:
  useRootAsPackage: true
