name: lucid_clip
description: Modern clipboard manager app
version: 1.3.0+24
publish_to: none

environment:
  sdk: '>=3.8.0 <4.0.0'

dependencies:
  app_links: ^6.3.2
  auto_route: ^11.1.0
  auto_updater: ^1.0.0
  bloc: ^9.1.0
  cached_network_image: ^3.3.1
  clipboard: ^3.0.8
  contextmenu: ^3.0.0
  crypto: ^3.0.3
  device_info_plus: ^12.3.0
  dio: ^5.4.3+1
  drift: ^2.31.0
  drift_flutter: ^0.2.8
  equatable: ^2.0.5
  firebase_auth: ^6.1.3
  firebase_core: ^4.3.0
  firebase_crashlytics: ^5.0.6
  flexible_dropdown: ^1.0.8
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_dotenv: ^6.0.0
  flutter_highlight: ^0.7.0
  flutter_localizations:
    sdk: flutter
  flutter_secure_storage: ^10.0.0
  flutter_staggered_grid_view: ^0.7.0
  get_it: ^9.2.0
  google_fonts: ^8.0.0
  hotkey_manager: ^0.2.3
  hugeicons: ^1.1.4
  hydrated_bloc: ^10.1.1
  iconsax: ^0.0.8
  injectable: ^2.4.4
  intl: ^0.20.2
  jiffy: ^6.3.2
  json_annotation: ^4.9.0
  melos: ^7.4.0
  metalink_flutter: ^2.0.1
  package_info_plus: ^9.0.0
  pasteboard: ^0.4.0
  path: ^1.9.1
  path_provider: ^2.1.3
  percent_indicator: ^4.2.5
  permission_handler: ^12.0.1
  proper_filesize: ^1.0.2
  recase: ^4.1.0
  screen_retriever: ^0.2.0
  share_plus: ^12.0.1
  shimmer: ^3.0.0
  supabase_flutter: ^2.12.0
  tinycolor2: ^3.0.1
  toastification: ^3.0.3
  tray_manager: ^0.5.2
  url_launcher: ^6.2.6
  uuid: ^4.5.1
  window_manager: ^0.5.1

dev_dependencies:
  auto_route_generator: ^10.0.1
  bloc_test: ^10.0.0
  build_runner: ^2.4.9
  drift_dev: ^2.31.0
  flutter_gen_runner: ^5.6.0
  flutter_launcher_icons: ^0.14.4
  flutter_test:
    sdk: flutter
  injectable_generator: ^2.6.2
  json_serializable: ^6.8.0
  mocktail: ^1.0.4
  very_good_analysis: ^10.1.0

flutter:
  uses-material-design: true
  generate: true

  assets:
    - .env
    - assets/images/
    - assets/icons/

flutter_gen:
  output: lib/generated/
  line_length: 80

  integrations:
    flutter_svg: true

melos:
  useRootAsPackage: true

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  image_path: "assets/icons/icon.png"
  min_sdk_android: 21

  windows:
    generate: true
    image_path: "assets/icons/icon.ico"
    icon_size: 48

  macos:
    generate: true
    image_path: "assets/icons/icon.png"
